[Debug][SketchRNN] Add eps to avoid nan in reconstrution loss
Problem:
- torch.exp(-z / (2 * (1 - rho_xy ** 2)))  produces a NaN when
rho_xy is -1 or 1 (resulting in a divison by 0)
    - rho_xy is produced by a tanh

Solution:
- Added an epsilon to the torch.exp denominator.

NOTE:
- Magenta and hardmaru's handwriting generation reference
 implementations don't have this epsilon...

Debugging methods:

Ran decoder only skethrnn with 512-2048 (throws nan earlier). Nan is
still pretty infrequent... maybe related to data normalization?

1) Add with torch.autograd.detect_anomaly(). This prints out traceback
after nan in *backward* loss. This was enough to be helpful (traceback
show below).

However, this also a method to catch nan's in the forward pass (method 2),
which didn't work for me (the isinstance may be incorrect).

2) Forward pass nan hook

    def nan_hook(self, inp, output):
        if not isinstance(output, tuple):
            outputs = [output]
        else:
            outputs = output

        for i, out in enumerate(outputs):
            if isinstance(out, tuple):
                continue
            nan_mask = torch.isnan(out)
            if nan_mask.any():
                print("In", self.__class__.__name__)
                raise RuntimeError("Found NAN in output {i} at indices: ", nan_mask.nonzero(), "where:",
                                   out[nan_mask.nonzero()[:, 0].unique(sorted=True)])

    for submodule in model.modules():
        submodule.register_forward_hook(nan_hook)

----------------------------

Anomaly traceback:

$ CUDA_VISIBLE_DEVICES=7 PYTHONPATH=. python src/models/sketch_rnn.py --notes tmp --enc_dim 512 --dec_dim 2048 --model_type decoder
$y
Saving run data to: runs/sketchrnn/tmp-dec_dim_2048-enc_dim_512-model_type_decoder
Data already exists in this directory (presumably from a previous run)
Enter "y" if you are sure you want to remove all the old contents: Removing old contents
Creating directory and saving data
Saving code snapshot to: runs/sketchrnn/tmp-dec_dim_2048-enc_dim_512-model_type_decoder/code_snapshot
Saving: runs/sketchrnn/tmp-dec_dim_2048-enc_dim_512-model_type_decoder/hp.json
Command used to start program:
 src/models/sketch_rnn.py --notes tmp --enc_dim 512 --dec_dim 2048 --model_type decoder
Start time: November15_20-48-54
Loading cat (1/1)
Scale factor:  41.712997
Number of examples in train: 70000
Loading cat (1/1)
Scale factor:  41.712997
Number of examples in valid: 2500
Loading cat (1/1)
Scale factor:  41.712997
Number of examples in train: 70000

/u/echu/projects/research/hierarchical_learning/venv/lib/python3.6/site-packages/torch/nn/modules/rnn.py:51: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropou
t expects num_layers greater than 1, but got dropout=1.0 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
Number of trainable parameters:  17086587
/pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:57: UserWarning: Traceback of forward call that caused the error:
  File "src/models/sketch_rnn.py", line 501, in <module>
    model.train_loop()
  File "/u/echu/projects/research/hierarchical_learning/src/models/core/train_nn.py", line 142, in train_loop
    mean_losses = self.dataset_loop(self.tr_loader, epoch, is_train=True, writer=self.writer, tb_tag='train')
  File "/u/echu/projects/research/hierarchical_learning/src/models/core/train_nn.py", line 86, in dataset_loop
    result = self.one_forward_pass(batch)
  File "src/models/sketch_rnn.py", line 213, in one_forward_pass
    q)
  File "/u/echu/projects/research/hierarchical_learning/src/models/base/stroke_models.py", line 530, in reconstruction_loss
    LS = -torch.sum(mask * torch.log(1e-6 + torch.sum(pi * prob, 2))) / float(max_len * batch_size)

Traceback (most recent call last):
  File "src/models/sketch_rnn.py", line 501, in <module>
    model.train_loop()
  File "/u/echu/projects/research/hierarchical_learning/src/models/core/train_nn.py", line 142, in train_loop
    mean_losses = self.dataset_loop(self.tr_loader, epoch, is_train=True, writer=self.writer, tb_tag='train')
  File "/u/echu/projects/research/hierarchical_learning/src/models/core/train_nn.py", line 93, in dataset_loop
    result['loss'].backward()
  File "/u/echu/projects/research/hierarchical_learning/venv/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
      File "/u/echu/projects/research/hierarchical_learning/venv/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function 'LogBackward' returned nan values in its 0th output.